<?php
// il_handler.php - Handles the logic for sending emails, including signature selection

// ...existing code...

        $signatureStored   = trim((string)($client['signature_block'] ?? ''));

        $DEFAULT_RATIONALE = 'Rationale for recommendations';
        
        $clientMessage = implode("\n\n", [
            $greetingStored,
            $introTextStored,
            $closingTextStored
        ]);

        $rationaleText = $rationaleStored !== '' ? $rationaleStored : $DEFAULT_RATIONALE;

        /* --- FIX: PRIORITIZE DYNAMIC SIGNATURE FROM DROPDOWN --- */
        // Check if the frontend sent a custom signature based on the "Send As" selection
        $dynamicSignature = trim($_POST['custom_signature'] ?? '');

        if (!empty($dynamicSignature)) {
            // Priority 1: Use the signature generated by the Javascript dropdown
            $signatureBlock = $dynamicSignature;
        } elseif ($signatureStored !== '') {
            // Priority 2: Use the signature saved in the client's database record
            $signatureBlock = $signatureStored;
        } else {
            // Priority 3: Fallback to the default Relationship Manager
            $signatureBlock = generateSignatureBlock($rmData);
        }
        /* ------------------------------------------------------- */

        // ...existing code...
?>